spring:
    datasource:
        url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_USER}
        password: ${PROD_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 10MB