spring:
    datasource:
        url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_USER}
        password: ${PROD_DB_PASSWORD}
        driver-class-name: com.postgresql.Driver
        hikari:
            maximum-pool-size: 2
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

